apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vgxno6gnj-python
  janus-idp.io/tekton: vgxno6gnj-python
  backstage.io/kubernetes-id: vgxno6gnj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vgxno6gnj-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
