apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vgxno6gnj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vgxno6gnj-python 
  name: vgxno6gnj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vgxno6gnj-python 
